spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 1131
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Только проверка структуры
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    flyway:
      enabled: true
      baseline-on-migrate: true  # если БД уже существовала

app:
  jwt:
    secret: your0secret0must0be0at0least0640characters0long0and0preferably0random
    expiration-ms: 86400000  # 24 часа