spring:
  application:
    name: "portfolio-service-dev"
  jpa:
    properties:
      show-sql: true
      hibernate:
        format_sql:
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    ru.samara.pet.portfolio_service.security: DEBUG
  execution-time:
    enabled: true
    threshold-ms: 10


