server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
    ru.samara.pet.portfolio_service.security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: 1131
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Только проверка структуры
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    flyway:
      enabled: true
      baseline-on-migrate: true  # если БД уже существовала

app:
  jwt:
    secret: l3eAT2bjCIsQ2mlDQVoIEBZZyWk4YqFaUqf6pUIvWKQ=
    expiration-ms: 86400000  # 24 часа